- name: install asdf
  git:
    repo=git://github.com/asdf-vm/asdf.git
    version={{ asdf_version }}
    dest={{ asdf_folder }}
    clone=yes
    update=yes

- name: install asdf plugins
  command: "{{ asdf_bin }} plugin-add {{ item.name }} {{ item.git_url }}"
  with_items: "{{ asdf_plugins }}"
  register: cmd_result
  failed_when: "cmd_result != 0 and 'already added' not in cmd_result.stderr"
