- name: update pacman cache
  pacman: update_cache=yes

- name: install system packages
  pacman: name={{ item }} state=present update_cache=no
  with_items: "{{ system_packages }}"

- name: install user packages
  become: no
  packer: name={{ item }} state=present
  with_items: "{{ user_system_packages }}"

- name: add vbox module to be loaded at boot
  template: src=virtualbox.conf.j2 dest=/etc/modules-load.d/virtualbox.conf
