- name: update pacman cache
  pacman: update_cache=yes

- name: install system packages
  pacman: name={{ item }} state=present update_cache=no
  with_items: system_packages

- name: install user packages
  command: packer -S {{ item }} --noconfirm
  sudo: no
  with_items: user_system_packages

- name: add ssh settings
  lineinfile:
    dest: /etc/ssh/sshd_config
    state: "present"
    line: {{ item }}
  with_items:
    - "AllowGroups   wheel"
    - "PermitRootLogin no"

- name: load vbox modules
  modprobe: name={{ item }}
  with_items:
    - vboxdrv
    - vboxnetflt
    - vboxnetadp

- name: add vbox module to be loaded at boot
  template: src=virtualbox.conf.j2 dest=/etc/modules-load.d/virtualbox.conf


