---
local_root_path: "{{ role_path }}/../../.."
dotfiles_source_path: "{{ local_root_path }}/dotfiles"

user: "{{ lookup('env','LOCAL_PROVISIONING_USER') | default('pablo', true) }}"
group: "{{ lookup('env','LOCAL_PROVISIONING_GROUP') | default('users', true) }}"
home_folder: "{{ lookup('env','LOCAL_PROVISIONING_HOME') | default('/home/pablo', true) }}"
dotfiles_folder: "{{ home_folder }}/dotfiles/dotfiles"
fish_completions_folder: "{{ dotfiles_folder }}/.config/fish/completions"
vim_autoload_folder: ".local/share/nvim/site/autoload"

home_folders:
    - .virtualenvs
    - projects
    - "{{ vim_autoload_folder }}"

services:
  - sshd
  - docker

sshd_settings:
  - "AllowGroups   wheel"
  - "PermitRootLogin no"

asdf_version: v0.3.0

asdf_plugins:
  - name: erlang
    git_url: "https://github.com/asdf-vm/asdf-erlang.git"
  - name: elixir
    git_url: "https://github.com/asdf-vm/asdf-elixir"

asdf_folder: "{{ home_folder }}/.asdf"

asdf_bin: "{{ asdf_folder }}/bin/asdf"

fish_completion_scripts:
  - "https://raw.githubusercontent.com/tmuxinator/tmuxinator/master/completion/tmuxinator.fish"
  - "https://raw.githubusercontent.com/asdf-vm/asdf/master/completions/asdf.fish"
  - "https://raw.githubusercontent.com/docker/docker/master/contrib/completion/fish/docker.fish"
